echo "REACT_APP_NODE_ENV=$REACT_APP_NODE_ENV" >> .env.${REACT_APP_NODE_ENV}
echo "REACT_APP_BACKEND_URL=$REACT_APP_BACKEND_URL" >> .env.${REACT_APP_NODE_ENV}
echo "REACT_APP_SOCKET_HOST=$REACT_APP_SOCKET_HOST" >> .env.${REACT_APP_NODE_ENV}