/* eslint-disable import/prefer-default-export */
export const SET_RUNTIME_VARIABLE = 'SET_RUNTIME_VARIABLE';

export const GET_PRICE_DETAIL_START = 'market/GET_PRICE_DETAIL_START';
export const GET_PRICE_DETAIL_SUCCESS = 'market/GET_PRICE_DETAIL_SUCCESS';
export const GET_PRICE_DETAIL_FAIL = 'market/GET_PRICE_DETAIL_FAIL';
export const RESET_PRICE_DETAIL = 'market/RESET_PRICE_DETAIL';

export const GET_DEPOSIT_HISTORY_CASH_START =
  'cash/GET_DEPOSIT_HISTORY_CASH_START';
export const GET_DEPOSIT_HISTORY_CASH_SUCCESS =
  'cash/GET_DEPOSIT_HISTORY_CASH_SUCCESS';
export const GET_DEPOSIT_HISTORY_CASH_FAIL =
  'cash/GET_DEPOSIT_HISTORY_CASH_FAIL';

export const GET_WITHDRAW_HISTORY_CASH_START =
  'cash/GET_WITHDRAW_HISTORY_CASH_START';
export const GET_WITHDRAW_HISTORY_CASH_SUCCESS =
  'cash/GET_WITHDRAW_HISTORY_CASH_SUCCESS';
export const GET_WITHDRAW_HISTORY_CASH_FAIL =
  'cash/GET_WITHDRAW_HISTORY_CASH_FAIL';

export const LOGIN_START = 'auth/LOGIN_START';
export const LOGIN_SUCCESS = 'auth/LOGIN_SUCCESS';
export const LOGIN_SUCCESS_NOT_ACTIVE = 'auth/LOGIN_SUCCESS_NOT_ACTIVE';
export const LOGIN_FAIL = 'auth/LOGIN_FAIL';

export const VERIFY_IMAGE_START = 'auth/VERIFY_IMAGE_START';
export const VERIFY_IMAGE_SUCCESS = 'auth/VERIFY_IMAGE_SUCCESS';
export const VERIFY_IMAGE_FAIL = 'auth/VERIFY_IMAGE_FAIL';

export const LOGOUT_START = 'auth/LOGOUT_START';
export const LOGOUT_SUCCESS = 'auth/LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'auth/LOGOUT_FAIL';

export const REGISTER_START = 'auth/REGISTER_START';
export const REGISTER_SUCCESS = 'auth/REGISTER_SUCCESS';
export const REGISTER_FAIL = 'auth/REGISTER_FAIL';

export const UPDATE_USER_START = 'auth/UPDATE_USER_START';
export const UPDATE_USER_SUCCESS = 'auth/UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAIL = 'auth/UPDATE_USER_FAIL';

export const UPLOAD_AVATAR_START = 'auth/UPLOAD_AVATAR_START';
export const UPLOAD_AVATAR_SUCCESS = 'auth/UPLOAD_AVATAR_SUCCESS';
export const UPLOAD_AVATAR_FAIL = 'auth/UPLOAD_AVATAR_FAIL';

export const FORGOT_PASSWORD_START = 'FORGOT_PASSWORD_START';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL';

export const RESET_PASSWORD_START = 'RESET_PASSWORD_START';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';

export const UPDATE_PROFILE_START = 'auth/UPDATE_PROFILE_START';
export const UPDATE_PROFILE_SUCCESS = 'auth/UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAIL = 'auth/UPDATE_PROFILE_FAIL';

export const CHANGE_PASSWORD_START = 'auth/CHANGE_PASSWORD_START';
export const CHANGE_PASSWORD_SUCCESS = 'auth/CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAIL = 'auth/CHANGE_PASSWORD_FAIL';

export const GET_WALLETS_START = 'wallet/GET_WALLETS_START';
export const GET_WALLETS_SUCCESS = 'wallet/GET_WALLETS_SUCCESS';
export const GET_WALLETS_FAIL = 'wallet/GET_WALLETS_FAIL';

export const CLEAR_WALLET_DETAIL = 'wallet/CLEAR_WALLET_DETAIL';

export const GET_LIST_WALLET_START = 'wallet/GET_LIST_WALLET_START';
export const GET_LIST_WALLET_SUCCESS = 'wallet/GET_LIST_WALLET_SUCCESS';
export const GET_LIST_WALLET_FAIL = 'wallet/GET_LIST_WALLET_FAIL';

export const GET_DEPOSIT_BANK_LIST_START = 'cash/GET_DEPOSIT_BANK_LIST_START';
export const GET_DEPOSIT_BANK_LIST_SUCCESS =
  'cash/GET_DEPOSIT_BANK_LIST_SUCCESS';
export const GET_DEPOSIT_BANK_LIST_FAIL = 'cash/GET_DEPOSIT_BANK_LIST_FAIL';

export const GET_WITHDRAW_BANK_LIST_START = 'cash/GET_WITHDRAW_BANK_LIST_START';
export const GET_WITHDRAW_BANK_LIST_SUCCESS =
  'cash/GET_WITHDRAW_BANK_LIST_SUCCESS';
export const GET_WITHDRAW_BANK_LIST_FAIL = 'cash/GET_WITHDRAW_BANK_LIST_FAIL';

export const BANK_WITHDRAW_START = 'cash/BANK_WITHDRAW_START';
export const BANK_WITHDRAW_SUCCESS = 'cash/BANK_WITHDRAW_SUCCESS';
export const BANK_WITHDRAW_FAIL = 'cash/BANK_WITHDRAW_FAIL';

export const BANK_DEPOSIT_START = 'cash/BANK_DEPOSIT_START';
export const BANK_DEPOSIT_SUCCESS = 'cash/BANK_DEPOSIT_SUCCESS';
export const BANK_DEPOSIT_FAIL = 'cash/BANK_DEPOSIT_FAIL';

export const GET_WALLET_START = 'wallet/GET_WALLET_START';
export const GET_WALLET_SUCCESS = 'wallet/GET_WALLET_SUCCESS';
export const GET_WALLET_FAIL = 'wallet/GET_WALLET_FAIL';

export const CREATE_WALLET_START = 'wallet/CREATE_WALLET_START';
export const CREATE_WALLET_SUCCESS = 'wallet/CREATE_WALLET_SUCCESS';
export const CREATE_WALLET_FAIL = 'wallet/CREATE_WALLET_FAIL';

export const SEND_BALANCE_START = 'wallet/SEND_BALANCE_START';
export const SEND_BALANCE_SUCCESS = 'wallet/SEND_BALANCE_SUCCESS';
export const SEND_BALANCE_FAIL = 'wallet/SEND_BALANCE_FAIL';

export const GET_TRANSACTIONS_START = 'wallet/GET_TRANSACTIONS_START';
export const GET_TRANSACTIONS_SUCCESS = 'wallet/GET_TRANSACTIONS_SUCCESS';
export const GET_TRANSACTIONS_FAIL = 'wallet/GET_TRANSACTIONS_FAIL';

export const VERIFY_ACCOUNT_START = 'auth/VERIFY_ACCOUNT_START';
export const VERIFY_ACCOUNT_SUCCESS = 'auth/VERIFY_ACCOUNT_SUCCESS';
export const VERIFY_ACCOUNT_FAIL = 'auth/VERIFY_ACCOUNT_FAIL';

export const ACTIVATE_ACCOUNT_START = 'auth/ACTIVATE_ACCOUNT_START';
export const ACTIVATE_ACCOUNT_SUCCESS = 'auth/ACTIVATE_ACCOUNT_SUCCESS';
export const ACTIVATE_ACCOUNT_FAIL = 'auth/ACTIVATE_ACCOUNT_FAIL';

export const REQUEST_WITHDRAW_ACTION_START =
  'wallet/REQUEST_WITHDRAW_ACTION_START';
export const REQUEST_WITHDRAW_ACTION_SUCCESS =
  'wallet/REQUEST_WITHDRAW_ACTION_SUCCESS';
export const REQUEST_WITHDRAW_ACTION_FAIL =
  'wallet/REQUEST_WITHDRAW_ACTION_FAIL';

export const ACTIVE_USER_IP_START = 'user/ACTIVE_USER_IP_START';
export const ACTIVE_USER_IP_SUCCESS = 'user/ACTIVE_USER_IP_SUCCESS';
export const ACTIVE_USER_IP_FAIL = 'user/ACTIVE_USER_IP_FAIL';

export const UPDATE_LOCALES = 'app/UPDATE_LOCALES';

export const GET_DEPOSITS_START = 'wallet/GET_DEPOSITS_START';
export const GET_DEPOSITS_SUCCESS = 'wallet/GET_DEPOSITS_SUCCESS';
export const GET_DEPOSITS_FAIL = 'wallet/GET_DEPOSITS_FAIL';
export const CLEAR_WALLET_INFORMATION = 'wallet/CLEAR_WALLET_INFORMATION';

export const GOOGLE_AUTH_GENERATE_START =
  'google_auth/GOOGLE_AUTH_GENERATE_START';
export const GOOGLE_AUTH_GENERATE_SUCCESS =
  'google_auth/GOOGLE_AUTH_GENERATE_SUCCESS';
export const GOOGLE_AUTH_GENERATE_FAIL =
  'google_auth/GOOGLE_AUTH_GENERATE_FAIL';

export const GOOGLE_AUTH_INSERT_START = 'google_auth/GOOGLE_AUTH_INSERT_START';
export const GOOGLE_AUTH_INSERT_SUCCESS =
  'google_auth/GOOGLE_AUTH_INSERT_SUCCESS';
export const GOOGLE_AUTH_INSERT_FAIL = 'google_auth/GOOGLE_AUTH_INSERT_FAIL';

export const GOOGLE_AUTH_VERIFY_START = 'google_auth/GOOGLE_AUTH_VERIFY_START';
export const GOOGLE_AUTH_VERIFY_SUCCESS =
  'google_auth/GOOGLE_AUTH_VERIFY_SUCCESS';
export const GOOGLE_AUTH_VERIFY_FAIL = 'google_auth/GOOGLE_AUTH_VERIFY_FAIL';

export const GOOGLE_AUTH_HANDLE_START = 'google_auth/GOOGLE_AUTH_HANDLE_START';
export const GOOGLE_AUTH_HANDLE_SUCCESS =
  'google_auth/GOOGLE_AUTH_HANDLE_SUCCESS';
export const GOOGLE_AUTH_HANDLE_FAIL = 'google_auth/GOOGLE_AUTH_HANDLE_FAIL';

export const LOGIN_WITH_GOOGLE_AUTH_START =
  'google_auth/LOGIN_WITH_GOOGLE_AUTH_START';
export const LOGIN_WITH_GOOGLE_AUTH_SUCCESS =
  'google_auth/LOGIN_WITH_GOOGLE_AUTH_SUCCESS';
export const LOGIN_WITH_GOOGLE_AUTH_FAIL =
  'google_auth/LOGIN_WITH_GOOGLE_AUTH_FAIL';

export const NEWSLETTER_SUBSCRIBE_START = 'NEWSLETTER_SUBSCRIBE_START';
export const NEWSLETTER_SUBSCRIBE_SUCCESS = 'NEWSLETTER_SUBSCRIBE_SUCCESS';
export const NEWSLETTER_SUBSCRIBE_FAIL = 'NEWSLETTER_SUBSCRIBE_FAIL';

export const GET_COINSINFO_START = 'GET_COINSINFO_START';
export const GET_COINSINFO_SUCCESS = 'GET_COINSINFO_SUCCESS';
export const GET_COINSINFO_FAIL = 'GET_COINSINFO_FAIL';
export const GET_COINSINFO_BY_ID_START = 'GET_COINSINFO_BY_ID_START';
export const GET_COINSINFO_BY_ID_SUCCESS = 'GET_COINSINFO_BY_ID_SUCCESS';
export const GET_COINSINFO_BY_ID_FAIL = 'GET_COINSINFO_BY_ID_FAIL';
export const GET_WALLET_SUCCESS_FOR_COIN = 'GET_WALLET_SUCCESS_FOR_COIN';
export const GET_LIST_COIN_START = 'GET_LIST_COIN_START';
export const GET_LIST_COIN_SUCCESS = 'GET_LIST_COIN_SUCCESS';
export const GET_LIST_COIN_FAIL = 'GET_LIST_COIN_FAIL';

export const GET_ORDER_HISTORY_START = 'exchange/GET_ORDER_HISTORY_START';
export const GET_ORDER_HISTORY_SUCCESS = 'exchange/GET_ORDER_HISTORY_SUCCESS';
export const GET_ORDER_HISTORY_FAIL = 'exchange/GET_ORDER_HISTORY_FAIL';

export const GET_ORDER_HISTORY_FOR_ALL_COINS_START =
  'exchange/GET_ORDER_HISTORY_FOR_ALL_COINS_START';
export const GET_ORDER_HISTORY_FOR_ALL_COINS_SUCCESS =
  'exchange/GET_ORDER_HISTORY_FOR_ALL_COINS_SUCCESS';
export const GET_ORDER_HISTORY_FOR_ALL_COINS_FAIL =
  'exchange/GET_ORDER_HISTORY_FOR_ALL_COINS_FAIL';

export const GET_ORDER_OPENING_START = 'exchange/GET_ORDER_OPENING_START';
export const GET_ORDER_OPENING_SUCCESS = 'exchange/GET_ORDER_OPENING_SUCCESS';
export const GET_ORDER_OPENING_FAIL = 'exchange/GET_ORDER_OPENING_FAIL';

export const GET_ORDER_OPENING_FOR_ALL_COINS_START =
  'exchange/GET_ORDER_OPENING_FOR_ALL_COINS_START';
export const GET_ORDER_OPENING_FOR_ALL_COINS_SUCCESS =
  'exchange/GET_ORDER_OPENING_FOR_ALL_COINS_SUCCESS';
export const GET_ORDER_OPENING_FOR_ALL_COINS_FAIL =
  'exchange/GET_ORDER_OPENING_FOR_ALL_COINS_FAIL';

export const GET_ORDER_BOOK_BUY_START = 'exchange/GET_ORDER_BOOK_BUY_START';
export const GET_ORDER_BOOK_BUY_SUCCESS = 'exchange/GET_ORDER_BOOK_BUY_SUCCESS';
export const GET_ORDER_BOOK_BUY_FAIL = 'exchange/GET_ORDER_BOOK_BUY_FAIL';
export const RESET_ORDER_BOOK_BUY = 'exchange/RESET_ORDER_BOOK_BUY';

export const GET_ORDER_BOOK_SELL_START = 'exchange/GET_ORDER_BOOK_SELL_START';
export const GET_ORDER_BOOK_SELL_SUCCESS =
  'exchange/GET_ORDER_BOOK_SELL_SUCCESS';
export const GET_ORDER_BOOK_SELL_FAIL = 'exchange/GET_ORDER_BOOK_SELL_FAIL';
export const RESET_ORDER_BOOK_SELL = 'exchange/RESET_ORDER_BOOK_SELL';

export const BUY_START = 'exchange/BUY_START';
export const BUY_SUCCESS = 'exchange/BUY_SUCCESS';
export const BUY_FAIL = 'exchange/BUY_FAIL';
export const SELL_START = 'exchange/SELL_START';
export const SELL_SUCCESS = 'exchange/SELL_SUCCESS';
export const SELL_FAIL = 'exchange/SELL_FAIL';
export const CLEAR_EXCHANGE_INFORMATION = 'exchange/CLEAR_EXCHANGE_INFORMATION';
export const CANCEL_START = 'exchange/CANCEL_START';
export const CANCEL_SUCCESS = 'exchange/CANCEL_SUCCESS';
export const CANCEL_FAIL = 'exchange/CANCEL_FAIL';
export const UPDATE_START = 'coin/UPDATE_START';
export const UPDATE_SUCCESS = 'coin/UPDATE_SUCCESS';
export const UPDATE_FAIL = 'coin/UPDATE_FAIL';
export const COIN_DETAIL_UPDATE_START = 'coin/COIN_DETAIL_UPDATE_START';
export const COIN_DETAIL_UPDATE_SUCCESS = 'coin/COIN_DETAIL_UPDATE_SUCCESS';
export const COIN_DETAIL_UPDATE_FAIL = 'coin/COIN_DETAIL_UPDATE_FAIL';

export const WALLET_UPDATE_START = 'wallet/WALLET_UPDATE_START';
export const WALLET_UPDATE_SUCCESS = 'wallet/WALLET_UPDATE_SUCCESS';
export const WALLET_UPDATE_FAIL = 'wallet/WALLET_UPDATE_FAIL';

export const USER_DEPOSIT_REQUEST_START = 'wallet/USER_DEPOSIT_REQUEST_START';
export const USER_DEPOSIT_REQUEST_SUCCESS =
  'wallet/USER_DEPOSIT_REQUEST_SUCCESS';
export const USER_DEPOSIT_REQUEST_FAIL = 'wallet/USER_DEPOSIT_REQUEST_FAIL';

export const UPDATE_DEPOSIT_REQUEST_START =
  'wallet/UPDATE_DEPOSIT_REQUEST_START';
export const UPDATE_DEPOSIT_REQUEST_SUCCESS =
  'wallet/UPDATE_DEPOSIT_REQUEST_SUCCESS';
export const UPDATE_DEPOSIT_REQUEST_FAIL = 'wallet/UPDATE_DEPOSIT_REQUEST_FAIL';

export const GET_DEPOSIT_REQUEST_HISTORY_START =
  'wallet/GET_DEPOSIT_REQUEST_HISTORY_START';
export const GET_DEPOSIT_REQUEST_HISTORY_SUCCESS =
  'wallet/GET_DEPOSIT_REQUEST_HISTORY_SUCCESS';
export const GET_DEPOSIT_REQUEST_HISTORY_FAIL =
  'wallet/GET_DEPOSIT_REQUEST_HISTORY_FAIL';

export const GET_REFEREE_LIST_START = 'user/GET_REFEREE_LIST_START';
export const GET_REFEREE_LIST_SUCCESS = 'user/GET_REFEREE_LIST_SUCCESS';
export const GET_REFEREE_LIST_FAIL = 'user/GET_REFEREE_LIST_FAIL';

export const GET_REFEREE_DETAIL_START = 'user/GET_REFEREE_DETAIL_START';
export const GET_REFEREE_DETAIL_SUCCESS = 'user/GET_REFEREE_DETAIL_SUCCESS';
export const GET_REFEREE_DETAIL_FAIL = 'user/GET_REFEREE_DETAIL_FAIL';

export const GET_SETTING_START = 'wallet/GET_SETTING_START';
export const GET_SETTING_SUCCESS = 'wallet/GET_SETTING_SUCCESS';
export const GET_SETTING_FAIL = 'wallet/GET_SETTING_FAIL';

export const GET_NEWS_START = 'news/GET_NEWS_START';
export const GET_NEWS_SUCCESS = 'news/GET_NEWS_SUCCESS';
export const GET_NEWS_FAIL = 'news/GET_NEWS_FAIL';

export const GET_SLIDER_START = 'slider/GET_SLIDER_START';
export const GET_SLIDER_SUCCESS = 'slider/GET_SLIDER_SUCCESS';
export const GET_SLIDER_FAIL = 'slider/GET_SLIDER_FAIL';

export const GET_SETTINGS_START = 'settings/GET_SETTINGS_START';
export const GET_SETTINGS_SUCCESS = 'settings/GET_SETTINGS_SUCCESS';
export const GET_SETTINGS_FAIL = 'settings/GET_SETTINGS_FAIL';

export const GET_USER_GROUP_LIST_START =
  'userGroupComissison/GET_USER_GROUP_LIST_START';
export const GET_USER_GROUP_LIST_SUCCESS =
  'userGroupComissison/GET_USER_GROUP_LIST_SUCCESS';
export const GET_USER_GROUP_LIST_FAILED =
  'userGroupComissison/GET_USER_GROUP_LIST_FAILED';

export const SIMPLE_BUY_COIN_START = 'exchange/SIMPLE_BUY_COIN_START';
export const SIMPLE_BUY_COIN_SUCCESS = 'exchange/SIMPLE_BUY_COIN_SUCCESS';
export const SIMPLE_BUY_COIN_FAIL = 'exchange/SIMPLE_BUY_COIN_FAIL';

export const SIMPLE_SELL_COIN_START = 'exchange/SIMPLE_SELL_COIN_START';
export const SIMPLE_SELL_COIN_SUCCESS = 'exchange/SIMPLE_SELL_COIN_SUCCESS';
export const SIMPLE_SELL_COIN_FAIL = 'exchange/SIMPLE_SELL_COIN_FAIL';

export const GET_USER_LEVEL_DEFINITIONS_START =
  'userLevel/GET_USER_LEVEL_DEFINITIONS_START';
export const GET_USER_LEVEL_DEFINITIONS_SUCCESS =
  'userLevel/GET_USER_LEVEL_DEFINITIONS_SUCCESS';
export const GET_USER_LEVEL_DEFINITIONS_FAILED =
  'userLevel/GET_USER_LEVEL_DEFINITIONS_FAILED';

export const GET_CURRENT_USER_LEVEL_DEFINITIONS_START =
  'userLevel/GET_CURRENT_USER_LEVEL_DEFINITIONS_START';
export const GET_CURRENT_USER_LEVEL_DEFINITIONS_SUCCESS =
  'userLevel/GET_CURRENT_USER_LEVEL_DEFINITIONS_SUCCESS';
export const GET_CURRENT_USER_LEVEL_DEFINITIONS_FAILED =
  'userLevel/GET_CURRENT_USER_LEVEL_DEFINITIONS_FAILED';

export const GET_CUSTOMER_SERVICE_START = 'GET_CUSTOMER_SERVICE_START';
export const GET_CUSTOMER_SERVICE_SUCCESS = 'GET_CUSTOMER_SERVICE_SUCCESS';
export const GET_CUSTOMER_SERVICE_FAIL = 'GET_CUSTOMER_SERVICE_FAIL';

export const GET_USER_BANK_LIST_START = 'GET_USER_BANK_LIST_START';
export const GET_USER_BANK_LIST_SUCCESS = 'GET_USER_BANK_LIST_SUCCESS';
export const GET_USER_BANK_LIST_FAILED = 'GET_USER_BANK_LIST_FAILED';
export const ADD_USER_BANK_START = 'ADD_USER_BANK_START';
export const ADD_USER_BANK_SUCCESS = 'ADD_USER_BANK_SUCCESS';
export const ADD_USER_BANK_FAILED = 'ADD_USER_BANK_FAILED';
export const UPDATE_USER_BANK_START = 'UPDATE_USER_BANK_START';
export const UPDATE_USER_BANK_SUCCESS = 'UPDATE_USER_BANK_SUCCESS';
export const UPDATE_USER_BANK_FAILED = 'UPDATE_USER_BANK_FAILED';
export const DELETE_USER_BANK_START = 'DELETE_USER_BANK_START';
export const DELETE_USER_BANK_SUCCESS = 'DELETE_USER_BANK_SUCCESS';
export const DELETE_USER_BANK_FAILED = 'DELETE_USER_BANK_FAILED';

export const GET_USER_PROMOTION_INFO_START = 'GET_USER_PROMOTION_INFO_START';
export const GET_USER_PROMOTION_INFO_SUCCESS =
  'GET_USER_PROMOTION_INFO_SUCCESS';
export const GET_USER_PROMOTION_INFO_ERROR = 'GET_USER_PROMOTION_INFO_ERROR';

export const GET_ALL_TRADING_INFO_START = 'GET_ALL_TRADING_INFO_START';
export const GET_ALL_TRADING_INFO_SUCCESS = 'GET_ALL_TRADING_INFO_SUCCESS';
export const GET_ALL_TRADING_INFO_ERROR = 'GET_ALL_TRADING_INFO_ERROR';

export const FB_SHARING_TRANSACTION = 'FB_SHARING_TRANSACTION';
export const FB_SHARING_TRANSACTION_SUCCESS = 'FB_SHARING_TRANSACTION_SUCCESS';
export const FB_SHARING_TRANSACTION_FAIL = 'FB_SHARING_TRANSACTION_FAIL';

export const OTC_CREATE_ORDER = 'OTC_CREATE_ORDER';
export const OTC_CREATE_ORDER_SUCCESS = 'OTC_CREATE_ORDER_SUCCESS';
export const OTC_CREATE_ORDER_FAIL = 'OTC_CREATE_ORDER_FAIL';

export const OTC_GET_ORDER_BOOK = 'OTC_GET_ORDER_BOOK';
export const OTC_GET_ORDER_BOOK_SUCCESS = 'OTC_GET_ORDER_BOOK_SUCCESS';
export const OTC_GET_ORDER_BOOK_FAIL = 'OTC_GET_ORDER_BOOK_FAIL';

export const OTC_UPDATE_DATA_FROM_SOCKET = 'OTC_UPDATE_DATA_FROM_SOCKET';


export const SWAP_GET_LIST_COINS = 'SWAP_GET_LIST_COINS';
export const SWAP_GET_LIST_COINS_SUCCESS = 'SWAP_GET_LIST_COINS_SUCCESS';
export const SWAP_GET_LIST_COINS_FAIL = 'SWAP_GET_LIST_COINS_FAIL';
export const SWAP_GET_HISTORY = 'SWAP_GET_HISTORY';
export const SWAP_GET_HISTORY_SUCCESS = 'SWAP_GET_HISTORY_SUCCESS';
export const SWAP_GET_HISTORY_FAIL = 'SWAP_GET_HISTORY_FAIL';
export const SWAP_ESTIMATE = 'SWAP_ESTIMATE';
export const SWAP_ESTIMATE_SUCCESS = 'SWAP_ESTIMATE_SUCCESS';
export const SWAP_ESTIMATE_FAIL = 'SWAP_ESTIMATE_FAIL';
export const SWAP_ESTIMATE_RESET = 'SWAP_ESTIMATE_RESET';

export const OTC_CREATE_TRANSACTION = 'OTC_CREATE_TRANSACTION';
export const OTC_CREATE_TRANSACTION_SUCCESS = 'OTC_CREATE_TRANSACTION_SUCCESS';
export const OTC_CREATE_TRANSACTION_FAIL = 'OTC_CREATE_TRANSACTION_FAIL';

export const OTC_CANCEL_TRANSACTION = 'OTC_CANCEL_TRANSACTION';
export const OTC_CANCEL_TRANSACTION_SUCCESS = 'OTC_CANCEL_TRANSACTION_SUCCESS';
export const OTC_CANCEL_TRANSACTION_FAIL = 'OTC_CANCEL_TRANSACTION_FAIL';

export const OTC_APPROVE_TRANSACTION = 'OTC_APPROVE_TRANSACTION';
export const OTC_APPROVE_TRANSACTION_SUCCESS =
  'OTC_APPROVE_TRANSACTION_SUCCESS';
export const OTC_APPROVE_TRANSACTION_FAIL = 'OTC_APPROVE_TRANSACTION_FAIL';

export const OTC_BUYER_APPROVE_TRANSACTION = 'OTC_BUYER_APPROVE_TRANSACTION';

export const OTC_SELLER_APPROVE_TRANSACTION = 'OTC_SELLER_APPROVE_TRANSACTION';

export const OTC_CREATE_TRANSACTION_FOR_SELLER =
  'OTC_CREATE_TRANSACTION_FOR_SELLER';

export const OTC_BUYER_APPROVE_TRANSACTION_RESET =
  'OTC_BUYER_APPROVE_TRANSACTION_RESET';

export const OTC_SELLER_APPROVE_TRANSACTION_RESET =
  'OTC_SELLER_APPROVE_TRANSACTION_RESET';

export const OTC_CREATE_TRANSACTION_FOR_SELLER_RESET =
  'OTC_CREATE_TRANSACTION_FOR_SELLER_RESET';

export const OTC_SELLER_APPROVE_FOR_BUY_ORDER =
  'OTC_SELLER_APPROVE_FOR_BUY_ORDER';

export const OTC_GET_BANK_INFO = 'OTC_GET_BANK_INFO';
export const OTC_GET_BANK_INFO_SUCCESS = 'OTC_GET_BANK_INFO_SUCCESS';
export const OTC_GET_BANK_INFO_FAIL = 'OTC_GET_BANK_INFO_FAIL';
